### ISSUE TITLE
workplace_workplace_1 exited with code 127

### ISSUE THREAD

**Issue by mostafa-zaied** [harishanchu/workplace-backend#8]
Method 1 (With docker and docker-compose)
- this appear when run  `docker-compose up`
MY `docker-compose.yaml`
```
version: "2"
networks:
  mysql:
    driver: bridge
services:

  mysql:
    image: mysql:5.7.21
    networks:
      - mysql
    volumes:
      - ${PWD}/data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - ALLOW_EMPTY_PASSWORD=NO

  adminer:
    image: adminer
    networks:
      - mysql
    ports:
      - "8085:8080"

  workplace:
    build: .
    networks:
      - mysql
    ports:
      - "3000:3000"
    depends_on:
      - mysql


```
![image](https://user-images.githubusercontent.com/63561762/138620089-cd875a51-3446-45b8-a768-d97a113473b7.png)
![image](https://user-images.githubusercontent.com/63561762/138620223-224a3750-d9f2-4233-b0b5-3b885663c0af.png)
![image](https://user-images.githubusercontent.com/63561762/138620515-7c4bb4f8-b602-4463-9974-c948b45252ad.png)

I didn't change anything on `datasources.json` , How to solve this?
